### ISSUE TITLE
Error is thrown into console during the game and players cards are hidden

### ISSUE THREAD

**Issue by mateleshkavo** [acebusters/ab-web#544]
**Steps to reproduce:**

1. Go to http://beta.acebusters.com/login and login with valid credentials.
2. Join some table.
3. Repeat this steps in other browser with other player.
4. Wait for hand to start.
5. As SB call BB and check as BB to see flop.
6. As a first player to act - bet 1 BB.
7. Wait.

**Expected result:**

1. There are no errors during all players time.

**Actual result:**

1. Error is thrown into console.
2. Players cards are hidden.
3. https://www.screencast.com/t/8IWfYc9nmD

Defect No38 from [this sheet](https://docs.google.com/spreadsheets/d/1wVJqs0P_u7FPLrH-051UtHZPuzmFwN9xdlJbj73F574/edit#gid=0).

v0.8.0

**Comment by sunify** [comment]
Should be fixed with https://github.com/acebusters/ab-web/pull/842
