### ISSUE TITLE
Player doesn't see his cards

### ISSUE THREAD

**Issue by mateleshkavo** [acebusters/ab-web#554]
**Screenshot** - https://www.screencast.com/t/pNlxSowj4jT

**Video with an error** - https://www.screencast.com/t/ZuNNBRof

**Related error in sentry** - Bad Request: you submitted wrong cards - https://sentry.io/acebusters/web-poker/issues/295957883/

Possible related errors:

- https://sentry.io/acebusters/web-poker/issues/331882106/
- https://sentry.io/acebusters/web-poker/issues/326995443/

**Comment by troggy** [comment]
![image](https://user-images.githubusercontent.com/163447/32945838-0404e138-cba6-11e7-80fc-84b870a6b5f2.png)

**Comment by sunify** [comment]
Ok, i reproduced the issue:
1. Player make a bet (bb in my case)
2. bet request sent, backend returns cards
3. bet request sent again (don't know why yet) and backend returns error, cards overwriting with `undefined`
4. Player can't see his cards

https://sentry.io/acebusters/web-poker/issues/415199893/
