### ISSUE TITLE
Firefox doesn't recognize that I'm on Rinkeby Test Net

### ISSUE THREAD

**Issue by mateleshkavo** [acebusters/ab-web#622]
**Steps to reproduce:**

1. Go to http://dapp.acebusters.com/login and login using FireFox.
2. Go to Dashboard page and switch between tabs.
3. Make sure that your MetaMask is on Rinkeby Test Net.

**Expected result:**

1. There are no info messages about switching to Rinkeby.

**Actual result:**

1. On all tabs there are info messages about Rinkeby.
2. https://www.screencast.com/t/2onnvJvP3f
3. https://www.screencast.com/t/RovT1Y4atFe

Defect No50 from [this sheet](https://docs.google.com/spreadsheets/d/1wVJqs0P_u7FPLrH-051UtHZPuzmFwN9xdlJbj73F574/edit#gid=0).

v0.9.0

**Comment by sunify** [comment]
PR merged and should be released in couple days, so i closing the issue
