### ISSUE TITLE
If players bets more then other players stack this bet crashes

### ISSUE THREAD

**Issue by mateleshkavo** [acebusters/ab-web#630]
**Steps to reproduce:**

1. Go to http://dapp.acebusters.com/login and login.
2. Go to Lobby and Join some table.
3. Repeat this steps in other browser.
4. Wait for the turn to come and as a player with bigger stack go All-in.

**Expected result:**

1. Bet was successful.

**Actual result:**

1. Bet crashes.
2. https://www.screencast.com/t/Ef9TVROGHhkW

Defect No52 from [this sheet](https://docs.google.com/spreadsheets/d/1wVJqs0P_u7FPLrH-051UtHZPuzmFwN9xdlJbj73F574/edit#gid=0).

v0.9.0

**Comment by grabus** [comment]
seems it also was fixed by update `poker-helper`

**Comment by sunify** [comment]
@grabus move it to testing list on https://github.com/orgs/acebusters/projects/2

**Comment by mateleshkavo** [comment]
Not reproducible for me in v1.0.1
