### ISSUE TITLE
invest tab allows to send failing txns

### ISSUE THREAD

**Issue by johannbarbie** [acebusters/ab-web#641]
state of contract:
```
> pow.activeSupply.call(function(e,a){console.log(e,a.toNumber())});
null 629998206821935700
```
629,998 ABP are claimed
```
> pow.totalSupply.call(function(e,a){console.log(e,a.toNumber())});
null 630000000000000000
```
630,000 ABP can be claimed

even though there is only little power available, i can convert as much NTZ as I want, leading to failed tx.

<img width="882" alt="screen shot 2017-09-14 at 10 43 05 am" src="https://user-images.githubusercontent.com/659301/30420349-929e5cf2-9939-11e7-86d8-8f0bfb9a245b.png">

we need to improve this on many sides:
- i want to know what share my amount ABP is in total ABP (my % of share in economy)
- i want to know how much ABP is available to power-up
- if there is no ABP available, disable the input, give reason
- if ABP is available, tell user how much NTZ to convert to claim that.

[ x] ~Power Up will convert NTZ to ABP immediately so you can invest in the Acebuster's economy.~
should say something like:
`Power Up will convert NTZ to ABP and make you a shareholder in the Acebusters Economy. Holding ABP, you will profit from our growth and be able to vote on governance policies.`
best to check whitepaper for good wording.

**Comment by VonIobro** [comment]
powerUp limited by
```javascript
// ensure that more ABP than exists can not be requested
const powerUpMaxBabz = totalAvailPwr.mul(completeSupplyBabz.div(adjTotalSupplyPwr)).div(1000).round(0, BigNumber.ROUND_DOWN).mul(1000);
```
