### ISSUE TITLE
display dashboard address wich checksum, so i don't get a warning when depositing

### ISSUE THREAD

**Issue by johannbarbie** [acebusters/ab-web#680]
`Trying to deposit into my Nutz wallet 0x4cb982d3921d1e0cf27dfa65d51948051db6ffa6, and MEW says something about "address not checksumed"`

**Comment by troggy** [comment]
supporting link https://myetherwallet.groovehq.com/knowledge_base/topics/not-checksummed-shows-when-i-enter-an-address
