### ISSUE TITLE
As a player I want to have a custom field for bet/raise buttons

### ISSUE THREAD

**Issue by mateleshkavo** [acebusters/ab-web#691]
Right now it's possible to bet/raise only with 1BB step, but players should be able to bet/raise some custom amount - https://www.screencast.com/t/sz604OEWH

**Comment by Kroshkaboo** [comment]
hm, @sunify will you do it yourself?

**Comment by sunify** [comment]
@Kroshkaboo yeah, I just assigned you to the wrong issue, sorry :-)

**Comment by Kroshkaboo** [comment]
np :)
