### ISSUE TITLE
As a player I want to raise my bet/raise amount on 1 BB after 1 click on bet/raise slider

### ISSUE THREAD

**Issue by mateleshkavo** [acebusters/ab-web#692]
When players are in deep stacks it's almost impossible to bet/raise 3-4 BB cause bet/raise slider is very sensitive. It would be very helpful if after 1 click on bet/raise slider my bet/raise mount become bigger on 1 BB. I still should be able to click and hold on bet/raise slider for fast slider readjustment.

**Comment by grabus** [comment]
seems this issue is not actual.
http://take.ms/h8YVp

**Comment by sunify** [comment]
Nope
