### ISSUE TITLE
sometimes hands didn't balance

### ISSUE THREAD

**Issue by troggy** [acebusters/ab-web#712]
At some point I got a hand with 0 inputs but non-zero distributions.
That leads to negative rake → failing `table.net` tx

See hand 76 below

**Database:**
![image](https://user-images.githubusercontent.com/163447/31018533-2c876852-a535-11e7-99ba-e31fc61efc1a.png)

**Contract:**
```
Table address: 0x4b4a7da88f1f2e9672408e6e6406f969de44ba24
Token address: 0x84e18564498531da0858a36a44f60d24d8e947bd
lastHandNetted: 64
lastNettingRequestHandId: 76

Seat 0 -----------
Sender: 0x7abde1a6f239ca3ea9ff5cdf08a5abc5519627a5
Balance before netting: 40
Signer: 0xfa71be989ae5f7ee8a68ba65c05b4884f561a045
Exit hand: 76
Hand 65. In: 2. Out: 2.97
Hand 66. In: 1. Out: 0
Hand 67. In: 2. Out: 2.97
Hand 68. In: 1. Out: 0
Hand 69. In: 4. Out: 0
Hand 70. In: 1. Out: 0
Hand 71. In: 2. Out: 2.97
Hand 72. In: 1. Out: 0
Hand 73. In: 2. Out: 2.97
Hand 74. In: 1. Out: 0
Hand 75. In: 2. Out: 2.97
Hand 76. In: 0. Out: 0
Seat balance after netting: 35.85
Transfer: 35.85 to 0x7abde1a6f239ca3ea9ff5cdf08a5abc5519627a5

Seat 1 -----------
Sender: 0xdef2146b52df8e7ca11d858b053cbbbc35a3b6c6
Balance before netting: 40
Signer: 0x7b407c9f73b0b3c5da01bff1650ddad0c71e523a
Exit hand: 76
Hand 65. In: 1. Out: 0
Hand 66. In: 2. Out: 2.97
Hand 67. In: 1. Out: 0
Hand 68. In: 2. Out: 2.97
Hand 69. In: 7. Out: 10.89
Hand 70. In: 2. Out: 2.97
Hand 71. In: 1. Out: 0
Hand 72. In: 2. Out: 2.97
Hand 73. In: 1. Out: 0
Hand 74. In: 2. Out: 2.97
Hand 75. In: 1. Out: 0
Hand 76. In: 0. Out: 2.97
Seat balance after netting: 46.71
Transfer: 46.71 to 0xdef2146b52df8e7ca11d858b053cbbbc35a3b6c6

Sum of the seat balances: 82.56
Table balance: 80
Rake: -2.56
```

**Hand lineups:** https://gist.github.com/troggy/35fc70fd42f585fe7231f4d03444d450

**Comment by troggy** [comment]
Also it is possible for hand to have 0 distribution but non-zero inputs.

See hand 37 and 40
![image](https://user-images.githubusercontent.com/163447/31021415-6d10c068-a53e-11e7-9222-c774ad1490b6.png)

I was able to reproduce this case, looks like some race condition on the frontend.

Steps to reproduce:
1. player A: fold
2. player B: quickly press Sit out before the next hand starts

**Comment by troggy** [comment]
Environment: Sandbox v1.1.0_1506680549323

**Comment by troggy** [comment]
Sometimes it could be in form of missing inputs for one of the sits:

![image](https://user-images.githubusercontent.com/163447/31035766-e4d483ae-a571-11e7-8a54-b581fa4f4c76.png)

**Comment by johannbarbie** [comment]
i wonder how it is possible that we have 0 inputs, but > 0 outputs, because the outputs are calculated from the inputs:
https://github.com/acebusters/poker-helper/blob/develop/lib/helper.js#L874 (edited)

is it maybe only that the debug pane does not display the amounts of non-bet receipts? (sit-out/fold receipts also have a value, but are not bet receipts).

**Comment by troggy** [comment]
but the same is in contract, so it is not dispaly issue

**Comment by troggy** [comment]
just played the game on production:

![image](https://user-images.githubusercontent.com/163447/31037380-46068620-a579-11e7-9e27-1ac8e00a7e5d.png)

**Comment by troggy** [comment]
managed to reproduce on of the cases:
![image](https://user-images.githubusercontent.com/163447/31103016-73b91112-a7dd-11e7-8af0-76b662ab7c98.png)

When new hand is dealing, press "Sit out" AFTER the opponent got his cards and posted a blind, but BEFORE you posted your blind. Since the app is not blazing fast it is quite achievable

**Comment by troggy** [comment]
Probably related issue: https://github.com/acebusters/ab-web/issues/726

**Comment by sunify** [comment]
Looks like all cases are fixed and i can't find new ones
