### ISSUE TITLE
Bad error message is shown when user confirms his email after link expiration

### ISSUE THREAD

**Issue by mateleshkavo** [acebusters/ab-web#714]
**Steps to reproduce:**

1. Register new account.
2. Open link from confirmation email after few hours.

**Expected:**

1. Error message says - 'Confirmation link is expired, please click here for a new link'.

**Actual:**

1. Error message says - 'Email Confirmation failed with error code Error'.
2. https://www.screencast.com/t/bAqxC8aZv9c

**Comment by sunify** [comment]
@johannbarbie are we really need TTL for the receipt?

**Comment by johannbarbie** [comment]
@sunify i think it is crucial for security.

One way to address this:
- check if receipt expired on client side, tell user to sign up again
- clean outdated signup attempts on backend

you see a different way?

**Comment by sunify** [comment]
@johannbarbie I agree with Victor's solution. Just checking before writing some code :-)

**Comment by johannbarbie** [comment]
also agree :)
