### ISSUE TITLE
Can't register user on staging, confirmation emails are not getting delivered

### ISSUE THREAD

**Issue by mateleshkavo** [acebusters/ab-web#723]
I can't register user on staging, confirmation emails are not getting delivered.

Comment from @sunify :

- You can’t signup on staging currently because we don’t have any proxies in the pool
- So frontend just not react properly on such response

**Comment by sunify** [comment]
Fixed in https://github.com/acebusters/account-service/commit/3b3499d9773bc715929e0aff6ce275c36380ae6b
