### ISSUE TITLE
invalid distribution value

### ISSUE THREAD

**Issue by troggy** [acebusters/ab-web#726]
Could be related to #712. For one of the hands inputs and outputs didn't balance, because distribution was smaller than it should be.

![image](https://user-images.githubusercontent.com/163447/31144226-b575b4f6-a888-11e7-9c8c-574e420eb4c8.png)

**Lineup for hand 39:**

```
[{
	"M": {
		"address": {
			"S": "0xfa71be989ae5f7ee8a68ba65c05b4884f561a045"
		},
		"last": {
			"S": "AqBF.vJ4HQSQexGNne3wMnJug75FharyKJNZlM+87muKLxu8=.CH3S7d7aJzR/ZxcjWNaK26Op3a6Bu4e7AqMmgj/zJq4=.G5njQwAAACcCAAAAAAfQAAAAAAAAAAAAAAAAAAAAAAA="
		},
		"sitout": {
			"N": "1507057612"
		}
	}
}, {
	"M": {
		"address": {
			"S": "0x7b407c9f73b0b3c5da01bff1650ddad0c71e523a"
		},
		"last": {
			"S": "AlI6.rbqPbNvKOm2jfkYkaYrFR7aCI2CwJdD8YQ93+HC+5r0=.K8vmeXriO3hRKRxaSmIsVjF6+APaic6OMntqBczF4jY=.HJnjQwAAACcCAAAAAAPoAAAAAAAAAAAAAAAAAAAAAAA="
		}
	}
}]
```
**Distribution for hand 39:**

```
{ signer: '0x82e8c6cf42c8d1ff9594b17a3f50e94a12cc860f',
  type: 21,
  handId: 39,
  claimId: 0,
  outs: 
   [ { [String: '0'] s: 1, e: 0, c: [Object] },
     { [String: '1980000000000'] s: 1, e: 12, c: [Object] } ] }
```

**All the hands from db:**
[poker (1).csv.zip](https://github.com/acebusters/ab-web/files/1353559/poker.1.csv.zip)

**Comment by troggy** [comment]
Two reproduce this I was folding al the hands preflop and trying to sit out quickly before the next hand starts.

Interesting thing about this issue is that distribution in hand 39 is incorrect in two ways:
1. wrong value. It looks like it didn't account small blind when calculated.
2. wrong winner! Distribution should have awarded the pot to BB, cause small blind folded

**Comment by sunify** [comment]
Interesting. Hand 39, seat 1 (small blind) has BET receipt, not FOLD. So winner was detected correctly (BB has a `sitout` flag), but distribution still incorrect. I noticed same bug last night and already on it

**Comment by troggy** [comment]
> Hand 39, seat 1 (small blind) has BET receipt, not FOLD. So winner is correct 

Hm.. During the game I (almost sure) pressed fold for the small blind

**Comment by sunify** [comment]
Hope we don't have two bugs here :-)

**Comment by sunify** [comment]
![image](https://user-images.githubusercontent.com/1477583/31172857-d240b392-a937-11e7-9323-f844d5686b78.png)

Wrong disribution fixed [here](https://github.com/acebusters/event-worker/commit/a475f3c93f1bbcc8d2c34eaf4608a5486d210cf2).

@troggy can you try to reproduce an issue with the wrong receipt in DB (BET instead of FOLD)?

**Comment by troggy** [comment]
@sunify is it on sandbox already?

**Comment by sunify** [comment]
@troggy yes

**Comment by troggy** [comment]
cannot reproduce. It worked perfectly

**Comment by troggy** [comment]
except the standup — it didn't work. But this is a different story

**Comment by troggy** [comment]
fixed with:
https://github.com/acebusters/poker-helper/commit/8858dd77decf085767e037c6b9a9eb93f65246dd
https://github.com/acebusters/poker-helper/commit/67b6a2c422ab27dc369534c76a0fb77caf00562f

**Comment by troggy** [comment]
Some observations:

![image](https://user-images.githubusercontent.com/163447/31194167-f81ff6c4-a94e-11e7-906e-e242d35fa45c.png)

No SB receipt (probably fine, cause I clicked sit out right before that). Distribution was calculated correctly :+1:
