### ISSUE TITLE
powerUp contract does not enforce minimum purchase

### ISSUE THREAD

**Issue by VonIobro** [acebusters/ab-web#741]
powerDown rejects if the amount is less than ~9.4 ABP (~36,000NTZ), this is correct behavior

While the current controller.minimumPowerUpBabz returns ~6,000NTZ, a user can powerUp as little as 400NTZ, which is incorrect behavior. The user should be limited to powerUp an amount of NTZ that is >= minimumPowerUpBabz. 

Currently the user is limited only via the UI for the minimum PowerUP amount.

**Comment by troggy** [comment]
There was a bug in `minimumPowerUpBabz` [fixed today](https://github.com/acebusters/economy/pull/53). I bet it should resolve this issue.

**Comment by troggy** [comment]
I will deploy new controller first thing tomorrow
