### ISSUE TITLE
Balance in table contract extremely high (infinity?)

### ISSUE THREAD

**Issue by sunify** [acebusters/ab-web#746]
![image](https://user-images.githubusercontent.com/1477583/31485529-bd4f98b0-af66-11e7-9634-069fc9f7dd53.png)

I played a lot of hands on this table with 3 players: 0x9bb67726be73e259ad5dae61b75849ae1b6382d7 (sandbox) and leave all players in sitout. When I returned to my laptop 2 was kicked and one was in standing-up (seat 3).

The last settle tx https://rinkeby.etherscan.io/tx/0x5f959ec8bbcf8477897b21d6bcea05db948c34fd40518ffa5a62a9b291ff0b91

**Comment by sunify** [comment]
Also i'm unable to join at this seat because estimate gas is too high

**Comment by troggy** [comment]
I think this might be because sandbox has broken stream scanner wth my experiments with settle

**Comment by troggy** [comment]
uploaded a stable stream-scanner

**Comment by sunify** [comment]
I think the issue is fixed
