### ISSUE TITLE
sometimes when i (re)load the page, balance is 0

### ISSUE THREAD

**Issue by johannbarbie** [acebusters/ab-web#755]
<img width="1027" alt="screen shot 2017-10-17 at 10 50 47 pm" src="https://user-images.githubusercontent.com/659301/31688817-d210df86-b38d-11e7-8ed5-8234385d4f9c.png">

minified code: `if(e)c.callbacks.forEach(function(t){t(e)}),s(e);else if(c.filterId=t,c.getLogsCallbacks.forEach(function(e){c.get(e)})`

version: `v1.2.0_1507292707803`

**Comment by VonIobro** [comment]
Hard reset to `https://dapp.acebusters.com/lobby` and then navigate to 'dashboard'. Styles are not showing up for the Dashboard tabs, but on refresh they eventually show up. This is very similar to the sandbox bug where the npm shrinkwrap file was messing with the package.json config. The solution was to completely remove the npm shrinkwrap file.

![image](https://user-images.githubusercontent.com/61939/31700686-4837cfc8-b3f5-11e7-9185-b6c0c2acb05f.png)

**Comment by sunify** [comment]
@VonIobro already reported in #756

**Comment by johannbarbie** [comment]
fixed the node, can't reproduce any more.
