### ISSUE TITLE
how can we improve the loading experience?

### ISSUE THREAD

**Issue by johannbarbie** [acebusters/ab-web#758]
we had some feedback about too long loading time for balances on dashboard.

ideas:
- more feedback (request taking longer, like gmail)
- basic connectivity test (client connection)
- geth caching

**Comment by sunify** [comment]
In version 1.3.0, it should be faster. There was a delay before adding the account information to the redux store, but it has now disappeared (https://github.com/acebusters/ab-web/pull/751)

Also, we can load balances when loading the app, not only on the dashboard loading. If you start with the Lobby page, you probably won't see any preloaders, and if you start with the Dashboard page a delay will be less.

**Comment by sunify** [comment]
Yeah, balances loading faster. You can check it in the PR
