### ISSUE TITLE
Player stuck in siting-in

### ISSUE THREAD

**Issue by troggy** [acebusters/ab-web#770]
I was sitting at the [table](https://dapp.acebusters.com/table/0x82efc836a756463fd910dfd1bcad681876fb9ea5) for quite a while. In `waiting`. At some point (dapp upgrade happened btw) I was put to sit out. Now if I press sit-in I am in `sitting-in` forever. If I press sit-out and sit-in again my bet in db increases.

Screenshot after two sit-out/sit-in cycles:
![image](https://user-images.githubusercontent.com/163447/32051110-0ecec896-ba5c-11e7-90fd-cf37400ddd8b.png)

**Comment by sunify** [comment]
What behavior are you expect? `waiting` status for the seat?

**Comment by troggy** [comment]
Yes, I expect to be in `waiting` after I sit it
