### ISSUE TITLE
as a user, I want tables to have human-readable names

### ISSUE THREAD

**Issue by VonIobro** [acebusters/ab-web#772]
Where can we find a list of fancy city names? Tree names? Other ideas?

Rough idea:
1. each table gets a name from the list based on tableId, ex. "Monaco"
2. do not reuse names, as there shouldn't be more than, say, 100+ tables ever.
2. However, if table-list is already used, append with 00#? ex "Monaco-001"

**Comment by sunify** [comment]
No need for numbers (from 3.). If we want a really big amount of names we can use two words. Eg color + tree name:
Red Oak
Blue Birch
Yellow Baobab

**Comment by troggy** [comment]
color + star names maybe? Places fromThe font we use on the site and in whitepaper creates that sci-fi feeling

**Comment by troggy** [comment]
OMG, there is a website for that https://namingschemes.com/

**Comment by sunify** [comment]
Also, we can use names of natural satellites in the solar system. Only Saturn + Jupiter gives us ≈100

**Comment by VonIobro** [comment]
I’d hope to get feedback from Calvin or the marketing guys before
implementing anything. Though I would vote for tree names... the Oak room (
also it goes with the nutz token)
