### ISSUE TITLE
as a user, I want to see better animations for table states

### ISSUE THREAD

**Issue by VonIobro** [acebusters/ab-web#780]
Focus of this issue:
- [x] holecard-entry animation
- [x] boardcard-entry animation
- [x] Winner animation
- [x] boardcard-exit animation
- [x] holecard-exit animation

Future issues?
- [ ] Pre flop animation
- [ ] Dealer chip animation?
- [ ] Chip animations

**Comment by troggy** [comment]
animation like "winning pot moves towards the winner" would be great. Noticed that on pokerstars — really nice feature
