### ISSUE TITLE
balance doesn't change after exchange until you refresh the page

### ISSUE THREAD

**Issue by troggy** [acebusters/ab-web#805]

**Comment by m-kroener** [comment]
<img width="579" alt="bildschirmfoto 2017-11-26 um 15 04 18" src="https://user-images.githubusercontent.com/31517309/33240751-786f13e2-d2bb-11e7-969c-56045f36d065.png">

verified ;)

**Comment by sunify** [comment]
Fixed in https://github.com/acebusters/ab-web/commit/3ecdca932564be1092739fc7d3409539edd0e748
