### ISSUE TITLE
On the overview, active power and total power are not the same.

### ISSUE THREAD

**Issue by m-kroener** [acebusters/ab-web#809]
Where is the missing power?

<img width="730" alt="bildschirmfoto 2017-11-26 um 14 41 16" src="https://user-images.githubusercontent.com/31517309/33240555-e3754336-d2b7-11e7-95d5-5b2485a43a92.png">

**Comment by sunify** [comment]
As I understand it should be the same. Similar amounts on the screenshot is just coincidence

@m-kroener
