### ISSUE TITLE
Transaction History shows transaction twice

### ISSUE THREAD

**Issue by m-kroener** [acebusters/ab-web#812]
somehow, the withdrawl is displayed twice. It is the same transaction. 

<img width="726" alt="bildschirmfoto 2017-11-26 um 14 59 12" src="https://user-images.githubusercontent.com/31517309/33240705-a97c7444-d2ba-11e7-8379-2f311360b466.png">

**Comment by sunify** [comment]
Fixed in https://github.com/acebusters/ab-web/commit/e774aafd6e145aa30790566df94d9e8096e1a7d8
