### ISSUE TITLE
refresh tables button keeps loading and loading

### ISSUE THREAD

**Issue by m-kroener** [acebusters/ab-web#814]
Left table after standup, then the button was loading and loading and the table still shows 2/2, but both players stood up. 

<img width="778" alt="bildschirmfoto 2017-11-26 um 15 31 17" src="https://user-images.githubusercontent.com/31517309/33240931-0834e58a-d2bf-11e7-92ca-ab4f1ae6eda0.png">

**Comment by sunify** [comment]
Related to 808

**Comment by sunify** [comment]
Not able to reproduce anymore. Possibly fixed with #835
