### ISSUE TITLE
No distribution on showdown

### ISSUE THREAD

**Issue by troggy** [acebusters/ab-web#826]
![image](https://user-images.githubusercontent.com/163447/33397703-8b2cfc20-d55d-11e7-9752-5573fd2ead5a.png)

**Comment by troggy** [comment]
write node wasn't working at thaat moment if that could be the reason

**Comment by sunify** [comment]
What table?

**Comment by troggy** [comment]
https://dapp.acebusters.com/table/0x81b94ee5dbe3c45aab492069928af651a83d052e

not sure if it will be possible to get anything from there cause I settled this table already

**Comment by troggy** [comment]
supposedly the mess was because of our ethereum nodes
